"""save ngrok username to settings

Revision ID: 616fe141adf9
Revises: 57e71dee0385
Create Date: 2026-01-21 15:19:27.556666

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # Added for SQLModel support
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "616fe141adf9"
down_revision: str | None = "57e71dee0385"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column("ngrok_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "ngrok_username")
    # ### end Alembic commands ###
