{{- if .Values.station.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syft-station.fullname" . }}-data
  labels:
    {{- include "syft-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: station
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.station.persistence.size | quote }}
  {{- with .Values.station.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
