"""add payment layer

Revision ID: 4346b239c3d2
Revises: b2c3d4e5f6a7
Create Date: 2026-03-21 19:50:45.138972

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # Added for SQLModel support
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4346b239c3d2"
down_revision: str | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("wallet_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "wallet_type", name="uq_wallet_tenant_type"),
    )
    op.create_index(op.f("ix_wallets_id"), "wallets", ["id"], unique=False)
    op.create_table(
        "bundle_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("endpoint_id", sa.Uuid(), nullable=True),
        sa.Column("user_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remaining_units", sa.Integer(), nullable=False),
        sa.Column("total_purchased", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "endpoint_id",
            "user_email",
            "unit_type",
            name="uq_bundle_usage_user_endpoint_type",
        ),
    )
    op.create_index(op.f("ix_bundle_usage_id"), "bundle_usage", ["id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("endpoint_id", sa.Uuid(), nullable=True),
        sa.Column("user_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checkout_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tier_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tier_units", sa.Integer(), nullable=False),
        sa.Column("unit_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("webhook_payload", sa.JSON(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_invoice_external_id", "invoices", ["external_id"], unique=True)
    op.create_index("idx_invoice_status", "invoices", ["status"], unique=False)
    op.create_index(
        "idx_invoice_tenant_user", "invoices", ["tenant_id", "user_email"], unique=False
    )
    op.create_index(op.f("ix_invoices_id"), "invoices", ["id"], unique=False)
    op.add_column(
        "endpoints",
        sa.Column(
            "archived", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "policies",
        sa.Column("policy_group", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_policies_policy_group"), "policies", ["policy_group"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policies_policy_group"), table_name="policies")
    op.drop_column("policies", "policy_group")
    op.drop_column("endpoints", "archived")
    op.drop_index(op.f("ix_invoices_id"), table_name="invoices")
    op.drop_index("idx_invoice_tenant_user", table_name="invoices")
    op.drop_index("idx_invoice_status", table_name="invoices")
    op.drop_index("idx_invoice_external_id", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_bundle_usage_id"), table_name="bundle_usage")
    op.drop_table("bundle_usage")
    op.drop_index(op.f("ix_wallets_id"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
