"""initial schema

Revision ID: 640a7f9a94e1
Revises:
Create Date: 2026-01-10 23:02:54.413937

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # Added for SQLModel support

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "640a7f9a94e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provisioner_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dtype", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("stopped_at", sa.DateTime(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dtype", name="uq_provisioner_dtype"),
    )
    op.create_index(
        "idx_provisioner_dtype", "provisioner_states", ["dtype"], unique=False
    )
    op.create_index(
        op.f("ix_provisioner_states_id"), "provisioner_states", ["id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_domain"), "tenants", ["domain"], unique=True)
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=True)
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dtype", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("provisioner_state_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provisioner_state_id"], ["provisioner_states.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_dataset_tenant_name"),
    )
    op.create_index(
        "idx_dataset_provisioner_state_id",
        "datasets",
        ["provisioner_state_id"],
        unique=False,
    )
    op.create_index(
        "idx_dataset_tenant_name", "datasets", ["tenant_id", "name"], unique=False
    )
    op.create_index(op.f("ix_datasets_id"), "datasets", ["id"], unique=False)
    op.create_table(
        "models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dtype", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_model_tenant_name"),
    )
    op.create_index(
        "idx_model_tenant_name", "models", ["tenant_id", "name"], unique=False
    )
    op.create_index(op.f("ix_models_id"), "models", ["id"], unique=False)
    op.create_table(
        "endpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("response_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published_to", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_endpoint_tenant_slug"),
    )
    op.create_index(
        "idx_endpoint_tenant_slug", "endpoints", ["tenant_id", "slug"], unique=False
    )
    op.create_index(op.f("ix_endpoints_id"), "endpoints", ["id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("policy_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=True),
        sa.Column("endpoint_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_id", "name", name="uq_policy_endpoint_name"),
    )
    op.create_index(
        "idx_policy_tenant_endpoint",
        "policies",
        ["tenant_id", "endpoint_id"],
        unique=False,
    )
    op.create_index(op.f("ix_policies_id"), "policies", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policies_id"), table_name="policies")
    op.drop_index("idx_policy_tenant_endpoint", table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_endpoints_id"), table_name="endpoints")
    op.drop_index("idx_endpoint_tenant_slug", table_name="endpoints")
    op.drop_table("endpoints")
    op.drop_index(op.f("ix_models_id"), table_name="models")
    op.drop_index("idx_model_tenant_name", table_name="models")
    op.drop_table("models")
    op.drop_index(op.f("ix_datasets_id"), table_name="datasets")
    op.drop_index("idx_dataset_tenant_name", table_name="datasets")
    op.drop_index("idx_dataset_provisioner_state_id", table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_domain"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_provisioner_states_id"), table_name="provisioner_states")
    op.drop_index("idx_provisioner_dtype", table_name="provisioner_states")
    op.drop_table("provisioner_states")
    # ### end Alembic commands ###
