"""initial schema

Revision ID: 1ae48660264f
Revises:
Create Date: 2026-07-17 15:10:13.508585

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # Added for SQLModel support
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ae48660264f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "space_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subdomain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reject_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("space_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_space_requests_owner_email"),
        "space_requests",
        ["owner_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_space_requests_status"), "space_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_space_requests_subdomain"),
        "space_requests",
        ["subdomain"],
        unique=False,
    )
    op.create_table(
        "space_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("revealed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_space_tokens_space_id"), "space_tokens", ["space_id"], unique=False
    )
    op.create_table(
        "spaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subdomain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spaces_owner_email"), "spaces", ["owner_email"], unique=False
    )
    op.create_index(op.f("ix_spaces_subdomain"), "spaces", ["subdomain"], unique=False)
    op.create_table(
        "station_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "supported_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("station_config")
    op.drop_index(op.f("ix_spaces_subdomain"), table_name="spaces")
    op.drop_index(op.f("ix_spaces_owner_email"), table_name="spaces")
    op.drop_table("spaces")
    op.drop_index(op.f("ix_space_tokens_space_id"), table_name="space_tokens")
    op.drop_table("space_tokens")
    op.drop_index(op.f("ix_space_requests_subdomain"), table_name="space_requests")
    op.drop_index(op.f("ix_space_requests_status"), table_name="space_requests")
    op.drop_index(op.f("ix_space_requests_owner_email"), table_name="space_requests")
    op.drop_table("space_requests")
    # ### end Alembic commands ###
