"""wallet hub identity (pat + owner user id)

Revision ID: 473130f36a71
Revises: 11af4f23a076
Create Date: 2026-07-28 13:44:56.480964

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # Added for SQLModel support
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "473130f36a71"
down_revision: str | None = "11af4f23a076"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("hub_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "wallets",
        sa.Column("hub_pat", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "hub_pat")
    op.drop_column("wallets", "hub_user_id")
    # ### end Alembic commands ###
